# Generated by Django 4.1.3 on 2022-12-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.ManyToManyField(to='main_app.bookmark'),
        ),
    ]
